version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'